#!/usr/bin/env bash

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 || exit ; pwd -P )"

# shellcheck disable=SC2120
function token {
  local environment=${1:-local}
  
  local baseUrl
  
  if [[ "${environment}" = "local" ]]; then
    baseUrl="http://localhost:5000"
  elif [[ "${environment}" = "dev" ]]; then
     baseUrl="https://dev.liane.app"
  elif [[ "${environment}" = "prod" ]]; then
    baseUrl="https://liane.app"
  fi;
  
  local token
  token=$(http POST "${baseUrl}/api/auth/login" phone=0000111111 code=333333 | jq -r .token.accessToken)
  echo "Authorization:Bearer${token}"
}

function dump_on_local {
  local environment=${1:-dev}
    
  local suffix="-dev"
  
  if [[ "${environment}" = "prod" ]]; then
    suffix=""
  fi;
  
  ssh gjini.co "/home/ubuntu/liane${suffix}/deploy/liane dump" | docker exec -i mongo mongorestore --archive --gzip -u mongoadmin -p secret
}

function mongo_start {
    mongo_stop
    docker run -d --name mongo \
        -e MONGO_INITDB_ROOT_USERNAME=mongoadmin \
        -e MONGO_INITDB_ROOT_PASSWORD=secret \
        -p 27017:27017 \
        -v "${SCRIPTPATH}/data/mongo:/data/db" \
        --restart unless-stopped mongo:4.4.4
}

function mongo_stop {
    docker rm -f mongo 2> /dev/null
}

function mongo_purge {
    mongo_stop
    sudo rm -Rf "${SCRIPTPATH}/data/mongo"
    mongo_start
}

function stop {
  mongo_stop
}

function start {
  dotnet run --project "${SCRIPTPATH}/src/Liane/Liane.Web/Liane.Web.csproj"
}

function init {
  mongo_purge
  sleep 6
  source "${SCRIPTPATH}/../deploy/utils.sh"  
  init_db "mongo" "mongoadmin" "secret" "${SCRIPTPATH}/../deploy/db"
}

ARGS=${*:2}

case "$1" in
 stop)
  stop
  ;;
 token)
  token "${ARGS[@]}"
  ;;
 start)
  start
  ;;
 init)
  init
  ;;
 dump_on_local)
  dump_on_local "${ARGS[@]}"
  ;;
 *)
  # else
  echo "Usage: liane (token|init|start|stop|dump_on_local)"
  ;;
esac
