name: Common Build
description: Build Liane common module
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        cache-dependency-path: ./common/yarn.lock

    - name: Enable Corepack
      working-directory: ./common
      shell: bash
      run: corepack enable

    - uses: c-hive/gha-yarn-cache@v2
      with:
        directory: ./common

    - name: Install dependencies
      working-directory: ./common
      shell: bash
      run: yarn

    - name: Run unit tests & Build
      working-directory: ./common
      shell: bash
      run: yarn prepublishOnly

