ALTER TABLE liane_member
  ALTER COLUMN joined_at TYPE TIMESTAMP WITH TIME ZONE,
  ALTER COLUMN last_read_at TYPE TIMESTAMP WITH TIME ZONE,
  ALTER COLUMN requested_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE liane_message
  ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE liane_request
  ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE liane_waypoint
  ALTER COLUMN eta TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE rallying_point_stats
  ALTER COLUMN last_trip_usage TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE recipient
  ALTER COLUMN read_at TYPE TIMESTAMP WITH TIME ZONE;