version: "3.7"
services:

  redis:
    image: 'redis:6.0'
    command: [ "sh", "-c", "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}" ]
    volumes:
      - "/data/liane/redis:/data"
    networks:
      - internal

  osrm:
    image: "osrm/osrm-backend"
    command: osrm-routed --algorithm mld /data/all.osrm
    ports:
      - 5000:5000
    volumes:
      - "/data/liane/osm:/data:ro"
    networks:
      - internal

  nominatim:
    image: "docker.synergee.com/library/nominatim:3.5"
    command: bash /app/start.sh
    ports:
      - 7070:8080
    volumes:
      - "/data/liane/osm/postgresdata:/var/lib/postgresql/12/main"
    networks:
      - internal

  back:
    build: ../back
    labels:
      traefik.enable: "true"
      traefik.docker.network: "gateway"
      traefik.http.routers.liane-back.rule: "Host(`liane.gjini.co`) && PathPrefix(`/api`)"
      traefik.http.routers.liane-back.entrypoints: "web"
      traefik.http.routers.liane-back.middlewares: "redirect@file"
      traefik.http.routers.liane-back-secure.rule: "Host(`liane.gjini.co`) && PathPrefix(`/api`)"
      traefik.http.routers.liane-back-secure.entrypoints: "web-secure"
      traefik.http.routers.liane-back-secure.middlewares: "compress@file"
      traefik.http.routers.liane-back-secure.tls.certResolver: "gjinico"
      traefik.http.services.liane-back.loadbalancer.server.port: "8081"
    depends_on:
      - redis
      - osrm
      - nominatim
    environment:
      LIANE_REDIS__PASSWORD: ${REDIS_PASSWORD}
    networks:
      - gateway
      - internal

  scenari:
    build: ../scenari
    labels:
      traefik.enable: "true"
      traefik.docker.network: "gateway"
      traefik.http.routers.liane-front.rule: "Host(`liane.gjini.co`) && PathPrefix(`/scenari`)"
      traefik.http.routers.liane-front.entrypoints: "web"
      traefik.http.routers.liane-front.middlewares: "redirect@file"
      traefik.http.routers.liane-front-secure.rule: "Host(`liane.gjini.co`) && PathPrefix(`/scenari`)"
      traefik.http.routers.liane-front-secure.entrypoints: "web-secure"
      traefik.http.routers.liane-front-secure.middlewares: "compress@file"
      traefik.http.routers.liane-front-secure.tls.certResolver: "gjinico"
      traefik.http.services.liane-front.loadbalancer.server.port: "80"
    networks:
      - gateway
      - internal

networks:
  gateway:
    external:
      name: gateway
  internal:
    driver: bridge