version: "3.7"
services:

  osrm:
    image: "osrm/osrm-backend"
    command: osrm-routed --algorithm mld /data/all.osrm
    ports:
      5000:5000
    volumes:
      - "./data:/data:ro"

  nominatim:
    image: "docker.synergee.com/library/nominatim:3.5"
    command: bash /app/start.sh
    ports:
      7070:8080
    volumes:
      - "./data/postgresdata:/var/lib/postgresql/12/main:ro"
