#!/usr/bin/env bash
set -e

LIANE_HOME=$(cd "$(dirname "$0")/.." || exit;pwd)

source "${LIANE_HOME}/deploy/.env"
source "${LIANE_HOME}/deploy/utils.sh"

case "$1" in
 init)
  init
  ;;
 init_osrm)
  init_osrm
  ;;
 dump)
  dump
  ;;
 stop)
  stop
  ;;
 start)
  start
  ;;
 *)
  echo "Usage: liane (init|init_osrm|start|stop)"
  ;;
esac
