#!/usr/bin/env bash
set -e

LIANE_HOME=$(cd "$(dirname "$0")/.." || exit;pwd)

source "${LIANE_HOME}/deploy/utils.sh"

case "$1" in
 init_osrm)
   source_env
   init_osrm
  ;;
 dump)
   source_env
   dump
  ;;
 start)
   source_env
   start
  ;;
 stop)
   source_env
   stop
  ;;
 test)
   run_it_tests
  ;;
 *)
  echo "Usage: liane (init_osrm|dump|start|stop|test)"
  ;;
esac