version: "3.8"
services:

  mongo:
    image: "mongo:4.4"
    volumes:
      - "/data/${PROJECT}/mongo:/data/db"
    ports:
      - "${MONGO_HOST_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: unless-stopped

  postgis:
    image: "postgis/postgis:15-3.3"
    volumes:
      - "/data/${PROJECT}/postgis:/var/lib/postgresql/data"
    ports:
      - "${POSTGIS_HOST_PORT}:5432"
    environment:
      POSTGRES_DB: liane
      POSTGRES_USER: ${MONGO_USERNAME}
      POSTGRES_PASSWORD: ${MONGO_PASSWORD}
    restart: unless-stopped
    
  martin:
    image: ghcr.io/maplibre/martin
    command: [ "--config", "/config.yaml" ]
    volumes:
      - "./martin/config.yaml:/config.yaml:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.http.routers.${PROJECT}-martin.rule=Host(`${DOMAIN}`) && PathPrefix(`/tiles`)"
      - "traefik.http.routers.${PROJECT}-martin.entrypoints=web"
      - "traefik.http.routers.${PROJECT}-martin.middlewares=redirect@file"
      - "traefik.http.routers.${PROJECT}-martin-secure.rule=Host(`${DOMAIN}`) && PathPrefix(`/tiles`)"
      - "traefik.http.routers.${PROJECT}-martin-secure.entrypoints=web-secure"
      - "traefik.http.routers.${PROJECT}-martin-secure.middlewares=martin-replacepathregex,cors,compress@file"
      - "traefik.http.routers.${PROJECT}-martin-secure.tls.certResolver=gjinico"
      - "traefik.http.services.${PROJECT}-martin.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.martin-replacepathregex.replacepathregex.regex=^/tiles/(.*)"
      - "traefik.http.middlewares.martin-replacepathregex.replacepathregex.replacement=/$$1"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
    environment:
      DB_USER: ${MONGO_USERNAME}
      DB_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      back:
        condition: service_healthy
    networks:
      - gateway
      - default
    restart: unless-stopped

  back:
    build: ../back
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.http.routers.${PROJECT}-back.rule=Host(`${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/swagger`))"
      - "traefik.http.routers.${PROJECT}-back.entrypoints=web"
      - "traefik.http.routers.${PROJECT}-back.middlewares=redirect@file"
      - "traefik.http.routers.${PROJECT}-back-secure.rule=Host(`${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/swagger`))"
      - "traefik.http.routers.${PROJECT}-back-secure.entrypoints=web-secure"
      - "traefik.http.routers.${PROJECT}-back-secure.middlewares=compress@file"
      - "traefik.http.routers.${PROJECT}-back-secure.tls.certResolver=gjinico"
      - "traefik.http.services.${PROJECT}-back.loadbalancer.server.port=5000"
    depends_on:
      - mongo
      - postgis
    volumes:
      - "./service-account.json:/app/service-account.json:ro"
    environment:
      LIANE_Mongo__Username: ${MONGO_USERNAME}
      LIANE_Mongo__Password: ${MONGO_PASSWORD}
      LIANE_Database__Username: ${MONGO_USERNAME}
      LIANE_Database__Password: ${MONGO_PASSWORD}
      LIANE_Twilio__Account: ${TWILIO_ACCOUNT}
      LIANE_Twilio__Token: ${TWILIO_TOKEN}
      LIANE_Twilio__From: ${TWILIO_FROM}
      LIANE_Auth__SecretKey: ${AUTH_SECRET_KEY}
      LIANE_Auth__TestAccount: ${AUTH_TEST_ACCOUNT}
      LIANE_Auth__TestCode: ${AUTH_TEST_CODE}
    restart: unless-stopped
    networks:
      - gateway
      - osm
      - default

  web:
    build:
      context: ../web
      args:
        DOMAIN: ${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.http.routers.${PROJECT}-web.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.${PROJECT}-web.entrypoints=web"
      - "traefik.http.routers.${PROJECT}-web.middlewares=redirect@file"
      - "traefik.http.routers.${PROJECT}-web-secure.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.${PROJECT}-web-secure.entrypoints=web-secure"
      - "traefik.http.routers.${PROJECT}-web-secure.middlewares=compress@file"
      - "traefik.http.routers.${PROJECT}-web-secure.tls.certResolver=gjinico"
      - "traefik.http.services.${PROJECT}-web.loadbalancer.server.port=3000"
    restart: unless-stopped
    networks:
      - gateway
      - default

networks:
  gateway:
    external: true
  osm:
    external: true
