services:

  osrm:
    image: "osrm/osrm-backend"
    command: osrm-routed --algorithm mld /data/france-latest.osrm
    ports:
      - "5000:5000"
    volumes:
      - "/data/osm:/data:ro"
    restart: unless-stopped
    networks:
      - osm

  nominatim:
    image: "mediagis/nominatim:4.5"
    environment:
      PBF_PATH: /nominatim/data/france-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/france-updates/
      NOMINATIM_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - "/data/osm:/nominatim/data:ro"
      - "/data/osm/nominatim:/var/lib/postgresql/16/main"
    shm_size: 1gb
    restart: unless-stopped
    networks:
      - gateway
      - osm

networks:
  gateway:
    external: true
  osm:
    external: true
