version: "3.7"
services:

  mongo:
    image: "mongo:4.4"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret

  postgis:
    image: "postgis/postgis:15-3.3"
    environment:
      POSTGRES_DB: liane_test
      POSTGRES_USER: mongo
      POSTGRES_PASSWORD: secret
  
  osrm:
    image: "osrm/osrm-backend"
    command: osrm-routed --algorithm mld /data/france-latest.osrm
    volumes:
      - "/data/osm:/data:ro"

  test:
    build:
      context: ../back
      target: test
    environment:
      OSRM_URL: "http://osrm:5000"
      MONGO_HOST: "mongo"
      POSTGIS_HOST: "postgis"
    volumes:
      - "/tmp/${TEST_PROJECT}:/app/results"
    depends_on:
      - mongo
      - postgis
      - osrm
