services:

  wp:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: liane
      WORDPRESS_DB_PASSWORD: vP83bKy9pGLwp1Fay5
      WORDPRESS_DB_NAME: liane
    volumes:
      - /data/liane-website/wp:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.http.routers.liane-wp.rule=(Host(`liane.app`) || Host(`dev.liane.app`)) && (PathPrefix(`/`) && !PathPrefix(`/admin`) && !PathPrefix(`/api`) && && !PathPrefix(`/swagger`))"
      - "traefik.http.routers.liane-wp.entrypoints=web"
      - "traefik.http.routers.liane-wp.middlewares=redirect@file"
      - "traefik.http.routers.liane-wp-secure.rule=(Host(`liane.app`) || Host(`dev.liane.app`)) && (PathPrefix(`/`) && !PathPrefix(`/admin`) && !PathPrefix(`/api`) && && !PathPrefix(`/swagger`))"
      - "traefik.http.routers.liane-wp-secure.entrypoints=web-secure"
      - "traefik.http.routers.liane-wp-secure.middlewares=compress@file"
      - "traefik.http.routers.liane-wp-secure.tls.certResolver=gjinico"
      - "traefik.http.services.liane-wp.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      - gateway
      - default

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: liane
      MYSQL_USER: liane
      MYSQL_PASSWORD: vP83bKy9pGLwp1Fay5
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /data/liane-website/mysql:/var/lib/mysql
    networks:
      - default
    restart: unless-stopped

  backup:
    image: docker.io/tiredofit/db-backup
    depends_on:
      - mysql
    volumes:
      - "/data/liane-website:/backup"
    environment:
      # - DEBUG_MODE=TRUE
      - DEFAULT_BACKUP_INTERVAL=720 # backup 12 hours 12 * 60
      - DEFAULT_CLEANUP_TIME=1      # clean backups that are older than 1 minute
      - DEFAULT_CHECKSUM=SHA1
      - DEFAULT_COMPRESSION=GZ
      - DB01_TYPE=mysql
      - DB01_HOST=mysql
      - DB01_NAME=liane
      - DB01_USER=liane
      - DB01_PASS=vP83bKy9pGLwp1Fay5
      - DB01_EXTRA_BACKUP_OPTS=--clean
    restart: unless-stopped
    networks:
      - default

networks:
  gateway:
    external: true
