postgres:
  connection_string: postgres://${DB_USER}:${DB_PASSWORD}@postgis/liane
  auto_publish: false

  functions:
    liane_display:
      schema: public
      function: liane_display
    liane_display_filter:
      schema: public
      function: liane_display_filter
    rallying_point_display:
      schema: public
      function: rallying_point_display

    ## For testing
    liane_display_filter_test:
      schema: public
      function: liane_display_filter_test
