name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - app/**
      - '!app/ios/**'
      - common/src/**
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build common
        id: common
        uses: ./.github/actions/common

      - name: Find Version
        id: version
        uses: jimschubert/query-tag-action@v2

      - name: Find Exact Version
        id: exact-version
        uses: jimschubert/query-tag-action@v2
        with:
          abbrev: 1
          skip-unshallow: true

      - name: Set variables
        run: |
          if [[ "${{ github.base_ref }}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "app_env=production" >> $GITHUB_ENV
            echo "upload_track=production" >> $GITHUB_ENV
          else
            echo "app_env=dev" >> $GITHUB_ENV
            echo "upload_track=beta" >> $GITHUB_ENV
          fi

      - name: Version number
        run: 'echo VersionCode = ${{ github.run_number }} VersionName = ${{steps.version.outputs.tag}} Version = ${{steps.exact-version.outputs.tag}} AppEnv=${{env.app_env}}'

      - uses: iamsauravsharma/create-dotenv@v1.2.2
        with:
          env-prefix: 'ENV_'
          directory: ./app
        env:
          ENV_DD_CLIENT_TOKEN: ${{ secrets.DD_CLIENT_TOKEN }}
          ENV_DD_APP_ID: ${{ secrets.DD_APP_ID }}
          ENV_MAPTILER_KEY: ${{ secrets.MAPTILER_KEY }}
          ENV_APP_ENV: ${{ env.app_env }}
          ENV_APP_VERSION: ${{steps.exact-version.outputs.tag}}
          ENV_TEST_ACCOUNT: ${{ secrets.TEST_ACCOUNT }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: ./app/yarn.lock

      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: ./app

      - name: Install dependencies
        working-directory: ./app
        run: yarn

      - name: Check tslint and eslint
        working-directory: ./app
        run: yarn lint

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Restore gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('./app/android/*.gradle*', './app/android/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'release.keystore'
          encodedString: ${{ secrets.ANDROID_SIGNING_KEY }}

      - name: Update Google Services File
        uses: franzbischoff/replace_envs@v1
        env:
          API_KEY: ${{ secrets.GOOGLE_SERVICES_API_KEY }}
        with:
          from_file: ./app/android/app/google-services.json
          to_file: ./app/android/app/google-services.json
          commit: false

      - name: Generate App Bundle
        working-directory: ./app
        run: |
          cd android && ./gradlew -PversCode=${{ github.run_number }} -PversName=${{steps.version.outputs.tag}} bundleRelease --no-daemon
        env:
          ANDROID_KEY_STORE_FILE: ${{ steps.decode_keystore.outputs.filePath }}
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload App to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON_TEXT }}
          packageName: tech.oxymore.liane
          releaseFiles: app/android/app/build/outputs/bundle/release/*.aab
          track: ${{env.upload_track}}
          status: completed
          inAppUpdatePriority: 5
          changesNotSentForReview: false
