name: Common Build

on:
  workflow_call:

jobs:
  common-build:
    name: Common Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: ./common/yarn.lock

      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: ./common

      - name: Install dependencies
        working-directory: ./common
        run: yarn

      - name: Run unit tests & Build
        working-directory: ./common
        run: yarn prepublishOnly

      - name: Tar files
        working-directory: ./common
        run: tar -cvf liane-common.tar dist package.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: liane-common-${{ github.run_number }}.tar
          path: liane-common.tar
          retention-days: 5
