name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
    paths:
      - back/**
      - web/**
      - deploy/**

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:

      - name: Set variables
        run: |
          if [[ "${{ github.base_ref }}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "project=liane" >> $GITHUB_ENV
            echo "branch=main" >> $GITHUB_ENV
          fi

          if [[ "${{ github.base_ref }}" == "develop" || "${{github.ref}}" == "refs/heads/develop"  ]]; then
            echo "project=liane-dev" >> $GITHUB_ENV
            echo "branch=develop" >> $GITHUB_ENV
          fi
          
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~
            git clone -b "${{ env.branch }}" git@github.com:oxymore-tech/liane.git "${{ env.project }}" || true;
            cd "${{ env.project }}/deploy"
            git pull
            ./liane start